#pragma kernel DrawAgentMap

struct Agent {
	float2 position;
	float angle;
};

RWStructuredBuffer<Agent> agents;
uint agentsLength;

RWTexture2D<float4> targetTexture;

[numthreads(16, 1, 1)]
void DrawAgentMap(uint3 id : SV_DispatchThreadID)
{
	if (id.x >= agentsLength)
		return;
	
	Agent agent = agents[id.x];
	targetTexture[int2((int)agent.position.x, (int)agent.position.y)] = 1; // Color agent position
}